name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo Display the timestamp2: $timestamp
        docker build . --file Dockerfile --tag daed.duckdns.org:50000/adebackstage:$GITHUB_SHA

    - name: Push the Docker image
      run: docker push daed.duckdns.org:50000/adebackstage:$GITHUB_SHA
